"""Module for creating GitHub Pull Requests to add missing models."""

import json
import os
from datetime import datetime

from github import Github, GithubException

from .browser_agent import FireworksModel

# Repository information
UPSTREAM_REPO = "BerriAI/litellm"
JSON_FILE_PATH = "model_prices_and_context_window.json"


def create_pull_request(
    missing_models: list[FireworksModel],
    updated_json: dict,
    github_token: str | None = None,
) -> str | None:
    """
    Create a Pull Request to add missing Fireworks models to LiteLLM.

    Args:
        missing_models: List of models to add
        updated_json: The complete updated JSON dictionary
        github_token: GitHub personal access token (uses GITHUB_TOKEN env var if not provided)

    Returns:
        URL of the created PR, or None if failed
    """
    token = github_token or os.environ.get("GITHUB_TOKEN")
    if not token:
        raise ValueError("GITHUB_TOKEN environment variable is required")

    g = Github(token)
    user = g.get_user()

    # Get or create fork
    upstream_repo = g.get_repo(UPSTREAM_REPO)
    fork = get_or_create_fork(user, upstream_repo)

    # Create branch name with timestamp
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    branch_name = f"add-fireworks-models-{timestamp}"

    # Get the default branch (usually 'main')
    default_branch = upstream_repo.default_branch

    # Create branch from upstream's default branch
    source_branch = upstream_repo.get_branch(default_branch)
    fork.create_git_ref(
        ref=f"refs/heads/{branch_name}",
        sha=source_branch.commit.sha,
    )

    # Update the JSON file in the fork
    file_content = json.dumps(updated_json, indent=2) + "\n"

    # Get the current file to get its SHA
    try:
        current_file = fork.get_contents(JSON_FILE_PATH, ref=branch_name)
        fork.update_file(
            path=JSON_FILE_PATH,
            message=f"Add {len(missing_models)} new Fireworks AI models",
            content=file_content,
            sha=current_file.sha,
            branch=branch_name,
        )
    except GithubException:
        # File doesn't exist, create it
        fork.create_file(
            path=JSON_FILE_PATH,
            message=f"Add {len(missing_models)} new Fireworks AI models",
            content=file_content,
            branch=branch_name,
        )

    # Create the Pull Request
    pr_title = f"Add {len(missing_models)} new Fireworks AI models"
    pr_body = generate_pr_body(missing_models)

    pr = upstream_repo.create_pull(
        title=pr_title,
        body=pr_body,
        head=f"{user.login}:{branch_name}",
        base=default_branch,
    )

    return pr.html_url


def get_or_create_fork(user, upstream_repo) -> object:
    """Get existing fork or create a new one."""
    # Check if user already has a fork
    try:
        fork = user.get_repo(upstream_repo.name)
        if fork.fork and fork.parent.full_name == UPSTREAM_REPO:
            return fork
    except GithubException:
        pass

    # Create new fork
    return user.create_fork(upstream_repo)


def generate_pr_body(missing_models: list[FireworksModel]) -> str:
    """Generate the PR description body."""
    model_list = "\n".join(
        f"- `fireworks_ai/{m.model_id}` - {m.name}" for m in missing_models[:50]
    )

    if len(missing_models) > 50:
        model_list += f"\n- ... and {len(missing_models) - 50} more models"

    # Group by type
    type_counts = {}
    for m in missing_models:
        type_counts[m.model_type] = type_counts.get(m.model_type, 0) + 1

    type_summary = ", ".join(f"{count} {t}" for t, count in sorted(type_counts.items()))

    body = f"""## Summary

This PR adds **{len(missing_models)} new Fireworks AI models** to the LiteLLM model pricing database.

### Model Types Added
{type_summary}

### Models Added

{model_list}

---

### How this PR was generated

This PR was automatically generated by the [Fireworks AI Cost Agent](https://github.com/ishaanjaffer/fireworks-ai-cost-agent), which:
1. Scraped the latest models from https://fireworks.ai/models
2. Compared against the existing LiteLLM model database
3. Added missing models with their current pricing

### Verification

Please verify the pricing information is accurate by checking https://fireworks.ai/models

"""
    return body


def sync_fork_with_upstream(fork, upstream_repo):
    """Sync the fork's default branch with upstream."""
    default_branch = upstream_repo.default_branch
    upstream_branch = upstream_repo.get_branch(default_branch)

    try:
        fork_branch = fork.get_branch(default_branch)
        if fork_branch.commit.sha != upstream_branch.commit.sha:
            # Update the fork's default branch
            fork.get_git_ref(f"heads/{default_branch}").edit(
                sha=upstream_branch.commit.sha, force=True
            )
    except GithubException:
        pass


if __name__ == "__main__":
    # Test generating PR body
    test_models = [
        FireworksModel(
            name="Test Model 1",
            model_id="test-model-1",
            input_cost_per_million=0.5,
            output_cost_per_million=1.0,
            unified_cost_per_million=None,
            context_window=32768,
            model_type="LLM",
        ),
        FireworksModel(
            name="Test Model 2",
            model_id="test-model-2",
            input_cost_per_million=None,
            output_cost_per_million=None,
            unified_cost_per_million=0.2,
            context_window=4096,
            model_type="Vision",
        ),
    ]

    print(generate_pr_body(test_models))

